#!/usr/bin/env bash
set -euo pipefail
MODEL_DIR=${1:-}
BASE=${2:-unknown}
if [[ -z "$MODEL_DIR" ]]; then echo "Usage: $0 <model_dir> [base_model]" >&2; exit 1; fi
cat > "$MODEL_DIR/Modelfile" <<EOF
FROM $(basename "$(ls "$MODEL_DIR"/*.gguf "$MODEL_DIR"/*.safetensors 2>/dev/null | head -n1)")
PARAMETER temperature 0.7
TEMPLATE "You are a helpful assistant."
LICENSE "MIT or Apache-2.0 (verify base model)"
# base_model: $BASE
# generated by package_modelfile.sh
EOF
