param(
  [Parameter(Mandatory=$true)][string]$ModelDir,
  [string]$BaseModel='unknown'
)

$files = Get-ChildItem $ModelDir -Include *.gguf,*.safetensors -File -Recurse | Select-Object -First 1
if (-not $files) { Write-Error 'No model artifact found'; exit 1 }
$artifact = Split-Path $files.FullName -Leaf

@"
FROM $artifact
PARAMETER temperature 0.7
TEMPLATE "You are a helpful assistant."
LICENSE "MIT or Apache-2.0 (verify base model)"
# base_model: $BaseModel
# generated by package_modelfile.ps1
"@ | Set-Content -Path (Join-Path $ModelDir 'Modelfile') -Encoding UTF8
