name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changelog-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate changelog
        run: |
          python scripts/generate_changelog.py >> CHANGELOG.md
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(changelog): update" || echo "no changes"
          git push || true
      - name: Decide release bump every 2 PRs
        id: decide
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.pulls.list({ owner: context.repo.owner, repo: context.repo.repo, state: 'closed' });
            const merged = prs.filter(p => p.merged_at).length;
            const forceMinor = (process.env.FORCE_MINOR || '').toLowerCase() === 'true';
            const bump = forceMinor ? 'minor' : (merged % 2 === 0 ? 'patch' : 'skip');
            core.setOutput('bump', bump);
      - name: Create release tag
        if: steps.decide.outputs.bump != 'skip'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.decide.outputs.bump }}
          release_branches: main
          tag_prefix: 'v'
      - name: Build Docker image tarball
        if: steps.decide.outputs.bump != 'skip'
        run: |
          docker build -f docker/Dockerfile -t llm-factory-ollama:${{ github.sha }} .
          docker save llm-factory-ollama:${{ github.sha }} -o llm-factory-ollama-${{ github.sha }}.tar
      - name: Create GitHub Release
        if: steps.decide.outputs.bump != 'skip'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            llm-factory-ollama-${{ github.sha }}.tar
